import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "@/app/StoreProvider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} bg-slate-50`}>
          <ToastContainer />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
